### ISSUE TITLE
Json-ld/Hydra Implementation

### ISSUE THREAD

**Issue by matlow** [vuex-orm/plugin-axios#100]
Hello,
Does anyone tried to use axios plugin to parse json-ld/hydra payload ?
Thx for reply

**Comment by thhan** [comment]
This feature will be awesome

**Comment by kiaking** [comment]
I don't think Vuex ORM Axios is going to support any specific API spec such as this or JSON API. Instead I think you can do that within `dataTransformer` config option 👍
