### ISSUE TITLE
Tag 0.5.1 troubles

### ISSUE THREAD

**Issue by AlekseyPn** [vuex-orm/plugin-axios#103]
We use 0.5.1, and i got error for update method, i call update without params and not pass id into params. Fix it please or help to resolve that error.

Fail code in Update.js.
`static onRequest(model, params) {
    return model.update({
      where: params.params.id,
      data: {
        $isUpdating: true,
        $updateErrors: []
      }
    })
  }`

Unfortunately we can’t upgrade to the new version any time soon

**Comment by kiaking** [comment]
Hmm... not sure why. What kind of error do you get?

**Comment by AlekseyPn** [comment]
> Hmm... not sure why. What kind of error do you get? 
id is not defined, because I dont need id. I passed simply id:1 and it work

**Comment by kiaking** [comment]
Sorry not sure what you mean here. What is not defined? You're getting an error right?

**Comment by AlekseyPn** [comment]
> Sorry not sure what you mean here. What is not defined? You're getting an error right?

Example from my code:
call model.$update(payload) - not pass params object, because in our backend we has PUT method without any params, includes id

After calling update i getting an error "id is not defined" because params undefined. And i need make little hack for call model.$update(payload, {params: {id: 1}}), when id is not real id.

Already it is not critical. We decide migrate on new version.

Thank for reply. :)

**Comment by kiaking** [comment]
Oh OK, thanks you do much!
