### ISSUE TITLE
Use custom action with $db().model('').action, Typescript types error.

### ISSUE THREAD

**Issue by steven0811** [vuex-orm/plugin-axios#107]
I'm using Nuxt.js + Typescript + vuex-orm with this plugin.

And `vuex-orm` docs recommend that use this.$store.$db() in SSR environment, and also recommend choose one method in same time (import or $db) [here](https://vuex-orm.github.io/vuex-orm/guide/model/retrieving-models.html#fetch-from-database).

But I'm facing a problem that typescript can't know that my custom action in Model.

![Screen Shot 2020-03-09 at 12 21 28 PM](https://user-images.githubusercontent.com/4948562/76182612-8343c480-6200-11ea-9130-81edca8411cd.png)

**Comment by kiaking** [comment]
Ah... good point. Yeah, maybe that custom typings might not work well with TypeScript. I don't think there would be an easy way to handle this... Hmmm...

For now, would it be possible for you to use a plain model method?

```js
class User extends Model {
  static fetchById (id) {
    return this.api().get(`/api/users/${id}`)
  }
}
```

**Comment by steven0811** [comment]
I found this [Fetch from Database](https://github.com/vuex-orm/vuex-orm/blob/84ff72baed5a56195d4ee4aa4df2fb679e11415f/docs/guide/model/retrieving-models.md#fetch-from-database)

```js
import Vue from 'vue'
import User from '@/models/User'

export default Vue.extend({
  computed: {
    User (): typeof User {
      return this.$store.$db().model(User)
    },

    users (): User[] {
      return this.User.all()
    }
  }
})
```

Problem solved, thanks.
