### ISSUE TITLE
Patch method / missing config implementation of "http.method"

### ISSUE THREAD

**Issue by geogeorgiev** [vuex-orm/plugin-axios#11]
Hi! The `method` option as in `methodConf.http.methods.$update.http.method` does not have any effect. In my case I wish to issue a `patch` request instead of a `put`. As far as I can see, it's not implemented, right? Do you plan to implement this config option?

**Comment by aveeday** [comment]
To update model in drf with PUT method all model fields required. It is like full replacement.
But with PATCH method it's possible to update not all fields. So it will be very helpful to have ability make update with PATCH.
https://www.django-rest-framework.org/api-guide/generic-views/#updatemodelmixin

**Comment by innovate-invent** [comment]
This appears to have been resolved by https://github.com/vuex-orm/plugin-axios/commit/b3ce9b45f534c191140a2770334b74b7de4eaf4e

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
