### ISSUE TITLE
model.api.get(url, config) ignores config.dataTransformer if config.save == false

### ISSUE THREAD

**Issue by maspio** [vuex-orm/plugin-axios#112]
### Szenario

- set [save == false](https://vuex-orm.github.io/plugin-axios/guide/configurations.html#save) to use a custom Model.save() function later

- set [dataTransformer ](https://vuex-orm.github.io/plugin-axios/guide/configurations.html#datatransformer)function to transform response to work with vuex-orm models

I also tried out setting safe after dataTransformer without success.

### Code

```javascript
Model.api().get(url, {
  save: false,
  dataTransformer: ({ data, headers }) => {
    // Do stuff with headers...
    // Do stuff with data...
    return data
  }
})
```

### Expected

Function dataTransformer should be called regardless of save configuration. At least I can't see why it shouldn't.

**Comment by cuebit** [comment]
The `dataTransformer` is designed to work with the `save` option. If you choose not to save then processing the response is entirely up to you. However, I do feel the transformer should be executable albeit manually. Something that’ll need to be considered.

In the meantime there are two avenues you could take to work around this:

1. Create a reusable transformer method that you can pass in the config but also use if you choose not to save, the outcome will be the same.

```js
const dataTransformer = ({ data, headers }) = {
  // Do stuff with headers...
  // Do stuff with data...
  return data
}

// With save
Model.api().get(url, { dataTransformer })

// Without save
Model.api().get(url, { save: false }).then(dataTransformer)
```

2. Call `getDataFromResponse` to invoke the transformer and return the expected transformed response, which will probably be your preferred approach.

```js
const request = await Model.api().get(url, {
  save: false,
  dataTransformer: ({ data, headers }) = {
    // Do stuff with headers...
    // Do stuff with data...
    return data
  }
})

// Invoke the `dataTransformer`
const response = request.getDataFromResponse()
```

There's about 99 ways to achieve this but you get the gist...

**Comment by kiaking** [comment]
@maspio Hi! Do you have any updates on this?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything 👍
