### ISSUE TITLE
Documentation improvement for non-get method options

### ISSUE THREAD

**Issue by brendon** [vuex-orm/plugin-axios#115]
#### Describe the improvement

The documentation tends to lack examples for other methods like `put()` and `post()`. While the methods are documented with their argument signatures, it took me a while to figure out I needed to pass `{save: false}` as a third argument to `put()` for example because the examples of this config only show `get()` :D

**Comment by kiaking** [comment]
Ah, good point. Yeah we should add those examples as well.

**Comment by cuebit** [comment]
FYI there is a PR that addresses this to some extent.  #117
