### ISSUE TITLE
How to make subsequent requests in fetch?

### ISSUE THREAD

**Issue by DQvsRA** [vuex-orm/plugin-axios#116]
I want to load more data after got first response, and then merge all results together, it's like paging, but second `await this.get(page_two_data_url)` replace first data.
```
static apiConfig = {
    actions: {
      async fetch (url) {
        const result = await this.get(`${url}`, { save: false })
        const redirect = result.response
        const data = redirect.data
        if (redirect.status === 200 && data.$type === 'redirect') {
          await this.get(data.redirectUrl, {
            dataTransformer: async (response) => {
              console.log('> HomePageContentModel -> fetch|redirect|response =', response)
              let data = Object.assign({}, response.data)
              const nextPage = response.data?.content.page.nextPage
              if (nextPage) {
                console.log('\t\t nextPage:', nextPage.href)
                const nextPageData = await this.get(nextPage.href)
                console.log('\t\t nextPage data:', nextPageData.response.data)
                data = Object.assign(nextPageData.response.data, data)
              }
              return data
            }
          })
        }
      }
    }
  }
```
this example a little bit more complicated it has `redirect`, but anyway, please help!

**Comment by DQvsRA** [comment]
Actually solve by setting `{ save: false }` on `await this.get(data.redirectUrl` and then merge two request together in third response in `dataTransformer`

**Comment by cuebit** [comment]
Glad you've managed resolved your issue, Vladimir!

Please don't hesitate to ping the community on [Slack](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTc1YTI2N2FjMGRlNGNmMzBkMGZlMmYxOTgzYzkzZDM2OTQ3OGExZDRkN2FmMGQ1MGJlOWM1NjU0MmRiN2VhYzQ) if you have any more questions.

👍
