### ISSUE TITLE
Custom methods in methodConf

### ISSUE THREAD

**Issue by kevrousso** [vuex-orm/plugin-axios#12]
Is there a way to implement our own methods other than the ones provided by default in methodConf of the model?
If so, how can I access it?
I tried to make one, but I don't have access to it by the model.

Thank you

**Comment by kevrousso** [comment]
This somewhat related to issue #7 as currently the methods in methodConf are managed by the plugin's interceptor.

**Comment by stygmate** [comment]
Hi ! i need to a had a $getperreference method to my model but when i call Bien.$getperreference(...params...) 
I get this error:
```
TypeError: _models_Bien__WEBPACK_IMPORTED_MODULE_8__.default.$getperreference is not a function
```

my methodConf:
``` javascript
    static methodConf = {
        http: {
            url: '/biens'
        },
        methods: {
            $fetch: {
                name: 'fetch',
                http: {
                    url: '/',
                    method: 'get',
                },
            },
            $get: {
                name: 'get',
                http: {
                    url: '/:id/',
                    method: 'get',
                },
            },
            $getperreference: {
                name: 'getperreference',
                http: {
                    url: '/per_reference/:id/',
                    method: 'get'
                },
            }
```

**Comment by anthonygore** [comment]
This won't work, only the predefined methods will work.

**Comment by lk77** [comment]
Hello,

you can have custom methods, just add a method to your class, and make your own logic, if it's something not standard, the package will not be able to handle it, so it's better to make your own axios call.

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
