### ISSUE TITLE
Data function support for insertOrUpdate method

### ISSUE THREAD

**Issue by kevrousso** [vuex-orm/plugin-axios#13]
I noticed that the `insertOrUpdate` method doesn't allow using a data function for nested properties. Without that, I am stuck using an `if-else` statement with update and insert like so:
```js
if (Project.find(id)) {
  Project.update({
    where: id,
    data(project) {
      project.permissions.canEdit = response.data.allowed;
    }
  });
} else {
  Project.insert({
    data: {
      id,
      permissions: {
        canEdit: response.data.allowed
      }
    }
  });
}
```
Is there any plan to support this in the future?

Thanks

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

The new version is using insertOrUpdate to insert data now 👍
