### ISSUE TITLE
Update relationships on fetch 

### ISSUE THREAD

**Issue by jlefebvre1997** [vuex-orm/plugin-axios#131]
Hello, more of a question than a feature request here 

Is it possible to update relationships when fetching related objects ? 
I use this placeholder API as an example : https://jsonplaceholder.typicode.com 

I defined a `User` model and an `Album` model. Is it possible to fetch the Albums, then fetch the Users and update the Albums with the user IDs ? 

Thanks in advance !

**Comment by cuebit** [comment]
Yes. The plugin handles the request and entity mutations for you, provided the API returns data in the correct format and adhere to the model schema you declare. 

Check out the docs for both Vuex ORM and this plugin for more details. You can also get help from the community [Slack channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTc1YTI2N2FjMGRlNGNmMzBkMGZlMmYxOTgzYzkzZDM2OTQ3OGExZDRkN2FmMGQ1MGJlOWM1NjU0MmRiN2VhYzQ). 👍
