### ISSUE TITLE
Inserting multiple records at once.

### ISSUE THREAD

**Issue by diegopamio** [vuex-orm/plugin-axios#132]
#### Is your feature request related to a problem? Please describe...

I'm adding a list of countries to the store, and it almost freezes the app, and when I look to the performance of vue components, it lists 270+ inserts from the plugin.

#### Describe the solution you'd like

Isn't possible to just make one mutation and send to vue-orm the array of results after the transformation?

#### Describe alternatives you've considered

N/A

#### Additional context

Using `dataTransformers` and loading ~ 270 records in one request. Doing the get inside a `waitFor` in the `mounted` method.

<img width="773" alt="CleanShot 2020-10-04 at 00 46 44@2x" src="https://user-images.githubusercontent.com/2249375/95006458-1f894a80-05db-11eb-973b-01d9ec10c371.png">

**Comment by PaintingCaves** [comment]
Hi there, I had a similar issue but it turns out you can perform your mutation and return the array of results. For example:

`static FetchAll({page = 1, limit = 15}, query = {}, relationships = []) {
        return this.api().get("/users", {
                params: {
                    ...{
                        page: page, limit: limit, with: relationships
                    }, ...(query !== {} ? query : {}),
                },
                dataTransformer: ({data: {data}}) => {
                    return data.map(user => {
                        return {...user, ...user.attributes}
                    })
                },
            }
        )
    }`

Where i'm sending the result of the .map() to the orm.

I hope this helps.

**Comment by cuebit** [comment]
Closing this as it's since been resolved over on Slack. 

For anyone washing up here, the number of mutations depend on whether data is being inserted or updated. Since updates are performed incrementally, the more updates performed the more mutations committed. To get the best out of performance when dealing with large data it's advised to use `insert` or `create` over `insertOrUpdate`.
