### ISSUE TITLE
axios config URL

### ISSUE THREAD

**Issue by rbayley** [vuex-orm/plugin-axios#137]
Hi everyone!

I am not sure this is a bug or I am misusing the config.
I am setting baseURL globally, and the URL on a model level.
```
  static apiConfig = {
    url: '/my/cool/path',
  }
```
My goal is NOT to write the URL every time I call myModel.api().get('my_path')....

Is this possible?

I thought it would be as stated on the [Configurations guide](https://vuex-orm.github.io/plugin-axios/guide/configurations.html) _Any axios options are permitted alongside any plugin options. Options are inherited in the same order, i.e. Global configuration is merged and preceded by Model configuration which is then merged and preceded by any Request configuration._

This leads me to configure baseURL globally and the URL on a model level.
[axios documentation](https://github.com/axios/axios#request-config) reads as follows:
  // `url` is the server URL that will be used for the request
  url: '/user',

  // `baseURL` will be prepended to `url` unless `url` is absolute.
  // It can be convenient to set `baseURL` for an instance of axios to pass relative URLs
  // to methods of that instance.
  baseURL: 'https://some-domain.com/api/',

please let me know if I am doing it wrong, or simply this is not a feature yet.

I think it would be a very good enhancement to have for every ACTION [get, post, etc... custom action] a URL path define in the model. This would help in fixing or updating code if "path" changes.

maybe something like:
```
  static apiConfig = {
    actionURLs: {
       get:'my/get/path',
       ....
      fetch:'/my/custom/action/path
    },
  }
```

looking forward to your reply

great plugin btw !!

**Comment by Nebucatnetzer** [comment]
Why did you close this @rbayley ?
Did you found a solution?
I was just wondering the same about defining an URL on the models and setting the baseURL globally.
