### ISSUE TITLE
Relationships dataKey

### ISSUE THREAD

**Issue by darkons** [vuex-orm/plugin-axios#138]
First of all, thank you for this awesome Vuex ORM plugin!

#### Is your feature request related to a problem? Please describe...

There is no way to apply a model relationship dataKey like main model request.

#### Describe the solution you'd like

Some API apps like mine return model relationships in nested key. For example:

`{
   "data":[
      {
         "object":"User",
         "id":"pg75k768",
         "name":"Admin",
         "email":"admin@admin.com",
         "roles":{
            "data":[
               {
                  "object":"Role",
                  "id":"pg75k768",
                  "name":"admin",
                  "description":"Administrator",
               }
            ]
         },
      }
   ],
}`

As you can see, "roles" relationship comes in nested dataKey (data) like main User model.

#### Describe alternatives you've considered

Applying same global dataKey to retrieve relationships is not correct because other users needs to retrieve relationships without nested key so, maybe a new dataKey for relationships can be added to configuration like:

`VuexORM.use(VuexORMAxios, {
  dataKey: 'data',
  relationDataKey: 'data',
})`

**Comment by cuebit** [comment]
Yea this would be useful. However, for most, this is generally not a key requirement. Since API's can appear different, it is down to the user to format the response how they see fit.
