### ISSUE TITLE
any plans for typescript support

### ISSUE THREAD

**Issue by Artessan** [vuex-orm/plugin-axios#15]
the vue-orm core support typescript implementation, have any plan to add support on this plugin???

**Comment by lino** [comment]
I'm gradually learning typescript, why don't we do it together? The maintainer seems to be busy with private family stuff, so it would be fair not to have any expectations.

**Comment by kiaking** [comment]
@Artessan Actually it is already pretty much supported! Just need more documentation I guess.

But I would really love to hear which part it is missing? (Declaration files are already there so you should get typings and such).

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

It's fully written in TS now! 👍
