### ISSUE TITLE
Cross-domain requests from node go to 127.0.0.1:80

### ISSUE THREAD

**Issue by KRaymundus** [vuex-orm/plugin-axios#17]
I get an error `connect ECONNREFUSED 127.0.0.1:80` when I do a cross domain request from my frontend server to my backend server on my Docker machine. They are on the same network. I properly added the baseURL (with proper casing) but didn't work. Spend some time debugging and found out the default config that is set in `/support/interfaces.js` has `proxy: {}` (an empty object).

Now that goes wrong in the http adapter. It checks for truthyness of the `proxy` option and if true it uses the `host` and `port` defined in that object, see the code [here](https://github.com/axios/axios/blob/master/lib/adapters/http.js#L148).

So the solution is to totally remove that (wrong) `proxy` default or set it to `false`.

**Comment by mmintel** [comment]
some news on this?

**Comment by mrFANRA** [comment]
Proxy does not work =(

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
