### ISSUE TITLE
Example app (like vuex-orm-example-nuxt)

### ISSUE THREAD

**Issue by twnaing** [vuex-orm/plugin-axios#20]
Do you have plan to do example app for `plugin-axios` on top of your example - [Vuex-ORM examples Nuxt](https://github.com/vuex-orm/vuex-orm-examples-nuxt)?

I am a noob at Vuejs and Nuxtjs and couldn't make it work by reading README of both repositories.

**Comment by pat123456** [comment]
+1
documentation is very succinct
should help a lot to have a variant of Vuex-ORM/ Nuxt example with plugin-axios added

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

And now it has a section on how to install it with Nuxt!
