### ISSUE TITLE
Allow injecting existing Axios instances

### ISSUE THREAD

**Issue by mrcageman** [vuex-orm/plugin-axios#22]
As many people are probably already using Axios in their project, it would be nice to allow us to inject an already existing instance of Axios as opposed to providing a new config all over.

**Comment by lino** [comment]
This is possible since #19, I'll provide a sample to you in a minute

**Comment by lino** [comment]
`VuexORM.use(VuexORMAxios, {
    database,
    http: {
        axios: yourAxiosInstance,
    }
})`

**Comment by mrcageman** [comment]
Missed this one, thanks for adding!
