### ISSUE TITLE
Mutating data from an API call

### ISSUE THREAD

**Issue by ZeroThe2nd** [vuex-orm/plugin-axios#23]
In the current version, there does not seem to be (or its undocumented) a way to mutate an API response before it's being saved/loaded etcetera.

Using an external API, which in my case provides far more information than is needed for the application to function, I only need a few values from an API response. However some are nested in sub-objects. While for the application I'm only in need of (for example) `member.username`, `memberships.active.id` and `displayName`, there currently is no way to "cherry pick" the desired data in a mutator function on a model or specific call.

Partially related to #21

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

You can cherry pick the field by creating only those field at Model schema definition 👍

**Comment by ZeroThe2nd** [comment]
While the new plugin version certainly cleans up some things, also making it less conflicting with other ORM plugins, it still does not provide a (documented) way to mutate a response before this is stored.

As for the updated way of handling the URL in the new `Model.api().[get|post|put|patch|delete]()` function, I think it's extra redundant code that is error sensitive if this is done for every place a model is used with the API. I'll make another issue after digging though the code, and provide a proposal if I come up with something nice. Same goes for the delete thing mentioned in the documentation.
