### ISSUE TITLE
Calling methods on model instance doesn't actually make request

### ISSUE THREAD

**Issue by innovate-invent** [vuex-orm/plugin-axios#26]
for example 

```javascript
const m = new MyModel();
m.$update({params:{id:123}, data:{mydata:'abc'}}); //Doesn't fire put request
MyModel.$update({params:{id:123}, data:{mydata:'abc'}}); //Works as expected
```

**Comment by KaniRobinson** [comment]
Well, if you look at the Core Vuex-ORM Library, you're initialising a creation method and trying to run an update from a non-completed model instance, you would do the second option which is...

```js
MyModel.$update({
  params:{
    id: 123
   }, 
  data:{
    mydata: 'abc'
  }
});
```

**Comment by innovate-invent** [comment]
Sorry, that was just from me trying to summarize my code.
How about this:

```javascript
const m = MyModel.find(123);
m.$update({params:{id:123}, data:{mydata:'abc'}}); //Doesn't fire put request
MyModel.$update({params:{id:123}, data:{mydata:'abc'}}); //Works as expected
```

**Comment by aveeday** [comment]
I think it will be more convenient in some cases to call instance methods e.g.:
```js
const user = User.find(10);
user.$delete();
```
Because usually objects saved in `data` or `computed` properties in vue for rendering, that's allow to use simple api:
```js
methods: {
  deleteCurrentUser() {
    this.user.$delete()
  }
}
````
For now it can be done with extra methods in model:
```js
class User extends Model {
  $delete() {
    User.$delete({
      params: {
        id: this.id,
      }
    });
  }
}
```
What about to include instance methods to library?
