### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by aveeday** [vuex-orm/plugin-axios#27]
How can I serialize and deserialize data before saving to server and vuex?

I would like to be able to store on server json data.

For example:
```js
class User extends Model {
  static fields () {
    return {
      id: this.attr(null),
      profile: this.jsonField(),
    }
  }
}

User.$create({
  data: {
    profile: { 
      imageUrl: 'http//example.com/image.jpg'
    }
  }
});

User.query().first().profile.imageUrl // => 'http//example.com/image.jpg'
```

For now I do:
```js
User.$create({
  data: {
    profile: JSON.stringify({ 
      imageUrl: 'http//example.com/image.jpg'
    })
  }
});

JSON.parse(User.query().first().profile).imageUrl // => 'http//example.com/image.jpg'
```
But it will be more convenient to make hidden serialization.

Related to #23 because also need some logic related to model before save data from API to vuex.

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
