### ISSUE TITLE
Merge http of method

### ISSUE THREAD

**Issue by innovate-invent** [vuex-orm/plugin-axios#29]
Currently the http of methodconf is merged with the context http block.
Please also merge the http block of the method to allow for different configuration per method.

For example, the request headers need to be different for a POST vs GET.

Currently the only means of doing this is via `transformRequest` in the methodconf http block. This feels hacky.

It would also be good to merge the http block passed to the method to allow per request customization of the config. ie.
```javascript
MyModel.$fetch({
    http: {
        onUploadProgress(){...}
        ...
    }
});
```

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
