### ISSUE TITLE
Better uri merge strategy

### ISSUE THREAD

**Issue by innovate-invent** [vuex-orm/plugin-axios#30]
The current merge strategy forces a uri prefix on the method. This is a problem when a REST API requires a totally different URI for a specific method or invocation.

It would be better to follow this merge criteria which is evaluated in order:
default (model) -> context -> methodConf -> method -> invocation (`$fetch({http:{uri:"..."}}`)

Criteria (evaluated in order):
- uri matches `^[^:]+://` discard current and return uri
- uri matches `^/` discard current and return uri (axios will apply baseURL)
- uri matches `^[^/]` append to current uri value with '/'

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
