### ISSUE TITLE
Unify config structure

### ISSUE THREAD

**Issue by innovate-invent** [vuex-orm/plugin-axios#31]
It would be good to unify the structure of the configurations across this plugin. For example currently the method invocation has a different structure and options than the methodConf block and individual method block. This makes documentation easier and allows overriding options at the different config levels.

A lodash merge of each of these configuration objects before evaluating the request would be ideal as described in https://github.com/vuex-orm/plugin-axios/issues/29

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
