### ISSUE TITLE
Better params handling

### ISSUE THREAD

**Issue by innovate-invent** [vuex-orm/plugin-axios#32]
Axios should handle appending params to the uri rather than [Action.js#L61](https://github.com/vuex-orm/plugin-axios/blob/2ed5dcd21a5178d68acecad7bdf087dc4f829a72/src/actions/Action.js#L61)
This should probably make use of Axios `paramsSerializer`.

The `query` option at method invocation should be discarded for `params` and any `:param` present in the uri should just flag the param for removal when passed to axios. This would leverage https://github.com/vuex-orm/plugin-axios/issues/29 and https://github.com/vuex-orm/plugin-axios/issues/31

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
