### ISSUE TITLE
All actions should return the model

### ISSUE THREAD

**Issue by innovate-invent** [vuex-orm/plugin-axios#35]
Currently the actions return the axios response. This is largely useless and causes the following pattern everywhere:

```javascript
let response = await Model.$fetch();
let fetchedModels = Model.query().where('id' a=>response.map(b=>b.id).includes(a)).get();
```

rather than

```javascript
let fetchedModels = await Model.$fetch();
```

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
