### ISSUE TITLE
Passing and array to "with"

### ISSUE THREAD

**Issue by ldiebold** [vuex-orm/plugin-axios#38]
Since vuex-orm is somewhat Laravel inspired, it would be great to be able to pass an array to "with"
```js
User.with(['clothes', 'posts.comments'])
```
Here's the [related documentation for Laravel](https://laravel.com/docs/5.8/eloquent-relationships#eager-loading)

Cheers!

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

BTW, you can do this in current version of Vuex ORM 👍

**Comment by ldiebold** [comment]
Oh, I posted this in the axios repo...
Where was my head at!

**Comment by kiaking** [comment]
haha lol
