### ISSUE TITLE
Repeated response handlers when working with provided Axios instance

### ISSUE THREAD

**Issue by lisandromc** [vuex-orm/plugin-axios#39]
Providing an axios instance like this:
```
VuexORM.use(VuexORMAxios, {
    http: {
        axios: axiosInstance,
  }
});
```
results in a response handler being added to the handlers list on each call, which in turns breaks proper response handling since each handler in the chain will return (and pass on) the `response.data` property.

This is usually not a problem because the Axios constructor does 
```
    this.instance = http.axios || axios.create(http);
```
so that a fresh axios instance is assigned each time. But it breaks as soon as the instance gets reused.

I'm submitting a pull request to fix this issue.

**Comment by olivergiess** [comment]
How is this tracking? This is several months old now, though I am still experiencing this issue, I can see the pull request has conflicts, what do we need to do to progress this?

**Comment by kiaking** [comment]
So sorry for your inconvinience! We've started a brand new implementation of this plugin at `next` branch. Please wait just a bit more!

**Comment by olivergiess** [comment]
@kiaking thanks I ended up forking and fixing the bug myself and refactoring the Actions for maintainability, as well as implementing the below.

I actually think that onResponse isn't the correct way to handle unwrapping the result of an API call, unless we deep clone the passed in Axios instance adding new handlers to it may affect other modules (this actually occurred to me). 

Seeing as the whole point of passing in an Axios instance is to consolidate the use of Axios across a project, I would propose we use a method along the lines of extractData which simply handles the result of a call as below (Using $fetch as an example).


```
try {
  const data = this.extractData(await request);

  await this.onSuccess(commit, model, data);
} catch(error) {
  this.onError(commit, error);
}
```

```
  /**
   * Extracts Data from response
   * @param {object} payload
   */
  static extractData(response)
  {
    return response.data;
  }
```

Furthermore by allowing `extractData` to be defined in config a project can handle any API response format (like JSON API).

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
