### ISSUE TITLE
Attach an image with FormData when using the $create model method [Axios instance]

### ISSUE THREAD

**Issue by russsiq** [vuex-orm/plugin-axios#41]
Example: we have a simple Vue component code to load an image

```javascript
...
    methods: {
        async upload(event) {
            let data = new FormData()

            data.append('file', this.takeFileFromInput(event, 'image.*'))

            let image = await FileModel.$create({data})

            this.$emit('input', image.id || null)
        },
...
```

But it won't work because in the file `@vuex-orm\plugin-axios\src\support\interfaces.js` has a field with an empty Data object, which is passed by default
https://github.com/vuex-orm/plugin-axios/blob/2ed5dcd21a5178d68acecad7bdf087dc4f829a72/src/support/interfaces.js#L41

**Comment by pat123456** [comment]
Hi, same problem, can't figure out how to upload file with vuex orm axios plugin ?

**Comment by russsiq** [comment]
Try this.

```javascript
// Import Vuex plugins.
import VuexORM from '@vuex-orm/core'
import VuexORMAxios from '@vuex-orm/plugin-axios'
import database from './database'
import http from './axios-request-config'

VuexORM.use(VuexORMAxios, {
    database,
    http,
})
```
```javascript
// axios-request-config.js

import axios from 'axios'

const http = {
  url: '/',
  method: 'get',
  baseURL: You api url,
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
  },
  // data: {}, Comment this line!!!
  ... Other config.
}

export default {
  axios: axios.create(http),
 ... Other config.
}
```

**Comment by pat123456** [comment]
Привет, спасибо за ответ.

With your solution it works better, the file is sent.
 
The problem now is that after the server response the new entry is not anymore automatically created in vuex orm. Same if I delete an entry, the entry is deleted in mysql database but not in vuex orm. 
Got this problem even if I don't comment // data: {}, just simply if I load axios-request-config.js in Vuex.use(...)

May I miss something ?

**Comment by russsiq** [comment]
Perhaps this will help you

1. https://gist.github.com/russsiq/cffd0735fd5736dd084c532395489b0e
1. https://github.com/vuex-orm/plugin-axios/issues/21#issuecomment-478163337

**Comment by pat123456** [comment]
thank again, but hard for me to understand what to do with your links

**Comment by russsiq** [comment]
Place your file `axios-request-config.js` in gist. I can help you.

**Comment by pat123456** [comment]
Hi,
I simply took the AxiosRequestConfig on plugin-axios [https://github.com/vuex-orm/plugin-axios](https://github.com/vuex-orm/plugin-axios) and comment the //data = {}

couldn't we just remove the data={} and keep the rest of the cofing as default ?

I don't understand why the data={} is problematic since we change it when doing :
`let formData = new FormData()
formData.append('file', this.file)
let port = await Portfolio.$create({data:formData})`
is "data={}" in config set data to json object only ?

here [https://github.com/axios/axios](https://github.com/axios/axios) they say "When no `transformRequest` is set, must be of one of the following types: ... Formdata"
is there somewhere to remove the 'trasformRequest' ?

sorry my dummies questions

**Comment by pat123456** [comment]
my axios-request-config.js
[https://gist.github.com/pat123456/2ee5ff79602e1aab6a17ee7f2684e686](https://gist.github.com/pat123456/2ee5ff79602e1aab6a17ee7f2684e686)

**Comment by pat123456** [comment]
when set data to string without loading axios-request-confing it's work well

`VuexORM.use(VuexORMAxios, {
  database,
  http: {
    baseURL: 'http://localhost/.../api/',
    url: '/',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    },
    data: ""
  }
})`

**Comment by russsiq** [comment]
https://github.com/vuex-orm/plugin-axios/issues/39

**Comment by russsiq** [comment]
I settled on this [version](https://gist.github.com/russsiq/cffd0735fd5736dd084c532395489b0e) with regard to this https://github.com/vuex-orm/plugin-axios/issues/39 and this https://github.com/vuex-orm/plugin-axios/issues/21 and this https://github.com/vuex-orm/plugin-axios/issues/42. Sorry for the comments in different languages.
