### ISSUE TITLE
Need to set headers  before on request

### ISSUE THREAD

**Issue by Uysim** [vuex-orm/plugin-axios#42]
Currently there is no way to inject custom headers

**Comment by simonini** [comment]
I have same problem for csrf reason.

**Comment by Tarasovych** [comment]
Same here

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

Now you can just directly pass preconfigured axios instance, so you could just set headers there. Or, it will take any axios config at request time, so you could pas it there too 👍
