### ISSUE TITLE
Events methods for models

### ISSUE THREAD

**Issue by akadlec** [vuex-orm/plugin-axios#44]
Is there a posibility to define custom event methods for each model?
eg.
For getting or fetching data:
```
static methodConf = {
    methods: {
      $get: {
        name: 'fetch',
        http: {
          url: '',
          method: 'get',
        },
        onResponse(response) {
           // format response data to match the model
           return data
        }
      },
   }
}
```

or for updating or creating:
```
static methodConf = {
    methods: {
      $update: {
        name: 'update',
        http: {
          url: '',
          method: 'patch',
        },
        onBeforeUpdate(data) {
          // Transform data to API acceptable...
          return data
        }
      },
   }
}
```

I am using JSON:API 1.1 with relations etc and it would be nice to have this feature

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
