### ISSUE TITLE
Usage with axios-extensions cacheAdapterEnhancer

### ISSUE THREAD

**Issue by mhluska** [vuex-orm/plugin-axios#46]
I'm wondering if it's possible to use this with [cacheAdapterEnhancer](https://github.com/kuitos/axios-extensions#cacheadapterenhancer). Namely, I would like to be able to conditionally disable caching when doing a request like `Model.$get({ cache: false, params: { id } })`. The `cache: false` option has no effect in this case.

I guess another way to ask this question is: is there a way to pass axios options through `Model.$get`?

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

Yes! Now you can pass **all** axios config to the api methods!
