### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by SargoDarya** [vuex-orm/plugin-axios#49]
Hey folks, there was no update for 1 1/2 months and there are 8 open pull requests. Are you guys looking for maintainers by any chance?

**Comment by kiaking** [comment]
@SargoDarya Actually yeah I think so. I was too lazy to handle this but I'll make some time and do something with it...! But yeah if there's anyone who can help, that would be great.

**Comment by olivergiess** [comment]
I'd be keen to contribute, how do I get involved?

**Comment by kiaking** [comment]
So sorry for your inconvinience! We've started a brand new implementation of this plugin at `next` branch. Please wait just a bit more! It would be great if you can give us the feedback for the `next` branch implementation though! Please join Vuex ORM slack channel and hit me!

**Comment by kiaking** [comment]
Finally, YES IT IS!

The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
