### ISSUE TITLE
"ReferenceError: window is not defined" when used with server-side rendering

### ISSUE THREAD

**Issue by davidsandoz** [vuex-orm/plugin-axios#5]
### Description
When using this plugin in a project that is server-side rendered, we get the error `ReferenceError: window is not defined` in`dist/index.js:1:278`, because `window` does not exist in a server-side environment.

### Expected behaviour
The plugin should be working with server-side rendering.

**Comment by KaniRobinson** [comment]
Issue is fixed in v0.1.2

**Comment by davidsandoz** [comment]
Thanks!
