### ISSUE TITLE
Nested Resources Support

### ISSUE THREAD

**Issue by wardy484** [vuex-orm/plugin-axios#50]
Does this plugin support nested resources? If so are the any examples of this? 

For example if I had a url like: `/lists/:list_id/items/:item_id`

**Comment by SebastianSmolorz** [comment]
If the endpoint returns a nested object, Vuex-ORM will create all nested related objects so long as you have the relationship set correctly. 

The `:param`  strings are replaced with the corresponding parameter passed into the API action e.g. `List.$update({query: {'list_id': 1, 'item_id': 1} })`.  So you could have a List model and an Item model, the Item model containing your url config, then you pass the list_id as a param.

**Comment by wardy484** [comment]
Great thanks I'll try that.
