### ISSUE TITLE
Classic mode for store/ is deprecated and will be removed in Nuxt 3.

### ISSUE THREAD

**Issue by Youdaman** [vuex-orm/plugin-axios#53]
If anyone else is getting the following warning in console:

```
Classic mode for store/ is deprecated and will be removed in Nuxt 3.
```
Edit store/index.js and change:
```
export default () => new Vuex.Store({
  plugins: [VuexORM.install(database)]
})
```
to:
```
export const plugins = [VuexORM.install(database)]
```
See also https://github.com/nuxt/nuxt.js/issues/4912

**Comment by kevinmarrec** [comment]
@Youdaman There is a way to not having to define store/index.js at all, you can look here : https://github.com/vuex-orm/plugin-graphql/blob/master/docs/guide/nuxt.md

**Comment by Youdaman** [comment]
@kevinmarrec yeah I think I've seen that approach with other Vuex plugins/addons. Thanks!

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

Now there's a section for installing the plugin with Nuxt.js!
