### ISSUE TITLE
What is "database"

### ISSUE THREAD

**Issue by stevage** [vuex-orm/plugin-axios#54]
In the readme, there is a reference to `database`:

`import database from './database'`

Presumably the user has to create this module. But what is it meant to contain? There's a real gap in the documentation here.

**Comment by SebastianSmolorz** [comment]
https://vuex-orm.github.io/vuex-orm/guide/components/database-and-registration.html

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

And there's no need to care about Database anymore : )
