### ISSUE TITLE
Broken IE11 and extra dependencies in Webpack output

### ISSUE THREAD

**Issue by kris-ellery** [vuex-orm/plugin-axios#55]
Hi there, I've recently started using Vuex ORM with Axios Plugin and noticed that the `dist/index.js` contains arrow function `.some(t=>t in i)`, which ultimately breaks IE11. Also, after running my bundle thru `webpack-bundle-analyzer` I noticed a bunch of extra dependencies like `pako`, `browserify-zlib`, and `node-libs-browser`. I assume none of that should be in there. Not sure if its a broken build, or something else at fault. Can you please shed some light on this? Thanks!

**Comment by mhluska** [comment]
I'm noticing this issue as well. The size of this package in the bundle is massive.

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

Now the bundle is super small! 1.54kb gzipped 👍
