### ISSUE TITLE
sharing with the plugin vuex-orm-localforage

### ISSUE THREAD

**Issue by UseMuse** [vuex-orm/plugin-axios#56]
I want to use plugin-axios plugin with vuex-orm-localforage plugin

Plugin-axios plugin has methods of the same name with plugin vuex-orm-localforage

eg:
### 1. plugin-axios:

Model Methods
```js
import User from '../models/User';

/**
 * @uri `/users`
 */
User.$fetch();
```
### 2. vuex-orm-localforage   
```js
import User from '../models/User';


/*
 Load data from the IndexedDB store associated to a model and persist them in the Vuex Store
 */
User.$fetch();
```

For plugin plugin-axios сhanging method name in methodConf does not work

**Comment by kiaking** [comment]
@UseMuse Uhh... yeah this is a problem. Currently, we are trying to change the method name for the plugins. Please give us time. We need to have some serious discussion.

**Comment by UseMuse** [comment]
@kiaking решение тут [https://github.com/eldomagan/vuex-orm-localforage/issues/6](url)
