### ISSUE TITLE
Plugin axios breaks Single Table Inheritance custom model fields

### ISSUE THREAD

**Issue by petertoth** [vuex-orm/plugin-axios#58]
Hi, 
I was playing around with Single Table Inheritance and found an issue with plugin-axios breaking custom fields on descendant models in STI.

My setup with STI:
```js
import { Model } from "@vuex-orm/core";

export default class Post extends Model {
  static entity = "posts";
  static primaryKey = "id";

  static types() {
    return {
      draft: DraftPost
    };
  }

  static fields() {
    return {
      id: this.increment(),
      title: this.string("")
    };
  }
}

export class DraftPost extends Post {
  static entity = "draft_posts";
  static baseEntity = "posts";

  static fields() {
    return {
      ...super.fields(),
      customDraftAttr: this.attr("")
    };
  }
}

// database.js
const database = new VuexORM.Database();
database.register(Post);
database.register(DraftPost);

VuexORM.use(VuexORMAxios, { database });

const store = new Vuex.Store({
  plugins: [VuexORM.install(database)]
});

```

When I insert a new **Post** with custom type the model instance is missing the fields defined in descendants of **Post**:

```js
Post
.insert({ data: { type: 'draft', title: 'Foo', customDraftAttr: 'bar' } })
.then(data => console.log(data))

Object {posts: Array[1]}
  posts: Array[1]
    0: DraftPost
    $id: 1
    $isUpdating: false
    $updateErrors: Array[0]
    $isDeleting: false
    $deleteErrors: Array[0]
    id: 1
    title: "Foo"
    <constructor>: "DraftPost"
```

As you can see the **customDraftAttr** is not present on the model instances. When I disable plugin-axios, my custom fields work just fine:

```js
// VuexORM.use(VuexORMAxios, { database });

Post
.insert({ data: { type: 'draft', title: 'Foo', customDraftAttr: 'bar' } })
.then(data => console.log(data))

Object {posts: Array[1]}
  posts: Array[1]
    0: DraftPost
    $id: 1
    id: 1
    title: "Foo"
    customDraftAttr: "bar"
    <constructor>: "DraftPost"
```

I looked at the source code of the plugin and found that model fields are being somehow cached here:
https://github.com/vuex-orm/plugin-axios/blob/70cc314bef15cae65bad9b973f5a255c93b11415/src/actions/Action.js#L30-L43

I presume when the base model is installed, it caches fields for the base class so `model.cachedFields` is already present on classes that inherit from the base model class.

Here's the repro sandbox: https://codesandbox.io/s/vuex-orm-sti-axios-bug-nl3vg

Cheers

**Comment by tvillaren** [comment]
Hello @petertoth, thanks for the report & digging into the code

I actually changed the way fields are cached when implementing STI (the cache is now a dictionary, see https://github.com/vuex-orm/vuex-orm/blob/master/src/model/Model.ts#L85) so the code in the plugin needs some update to reflect this change. @phortx do you want to have a look?

**Comment by phortx** [comment]
I don't maintain this plugin, it's from @KaniRobinson :)

**Comment by tvillaren** [comment]
Sorry, I read too fast, thought we were on the graphql plugin :)

**Comment by petertoth** [comment]
Hey @tvillaren, thanks a lot for clarification. The plugin just needs to update with the cached fields change. Any chance @KaniRobinson, @kiaking could look into this?

**Comment by kiaking** [comment]
@petertoth Thank you so much for the report! Yeah... I guess Axios Plugin is currently not compatible with STI. We're planning to make this plugin in more good shape! Sorry for the inconvenience but please wait a bit more...

**Comment by kiaking** [comment]
OK the new version is here! The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

Could you try with the new version to see if this still happens? I think it's fixed now.

**Comment by kiaking** [comment]
I hope this is fixed. So, I'll closing this one. Please feel free to open an another issue if there's anything!
