### ISSUE TITLE
Unable to add params to fetch

### ISSUE THREAD

**Issue by bluetetra** [vuex-orm/plugin-axios#6]
First of all, thank you for this wonderful plugin!  It has helped me quite a lot.  I did run into a snag that I hope you can help with.

I am stumped trying to add params to the fetch action.  

When I try this:
```
myModel.$fetch({
        params: {
          $limit: 100,
          $skip: 100
        }
      })
```
It ignores all of my params.  Is there a way to add params to the fetch?  Thanks again!

**Comment by malinushj** [comment]
@KaniRobinson Sure thing. I will strip any irrelevant data.
Folder.js:
```
import { Model } from '@vuex-orm/core';
import Post from '@app/models/Post';

export default class Folder extends Model {
  static entity = 'folders';

  static fields() {
    return {
      id: this.attr(null),
      title: this.attr(''),
      posts: this.hasMany(Post, 'folder_id'),
    };
  }

  static methodConf = {
    http: {
      url: '/user/folder'
    },
  }
}

```
And inside a component `create()` I call
```
// expected GET /api/user/folder?include=posts
// got GET /api/user/folder
Folder.$fetch({
      params: {
        include: 'posts'
      }
    });
```

**Comment by malinushj** [comment]
@KaniRobinson I managed to pinpoint the problem

**Comment by KaniRobinson** [comment]
@bluetetra and @malinushj I do appologise for the lack of documentation, i've been super busy with life, work and baby lol.

Example 1:
if you want your url to have params such as `/api/v1/users/:id`
```js
User.$fetch({
   params: { id: 1 }
})
```

Example 2:
If your url has query params such as `/api/v1/users?active=true`
```js
User.$fetch({
   query: { active: true }
})
```

Example 3:
if your url has both query params and a param such as `/api/v1/users/:id?active=true`
```js
User.$fetch({
   params: { id: 1 },
   query: { active: true }
})
```

**Comment by malinushj** [comment]
@bluetetra  Should be `query` instead of `params` inside the `$fetch`. Params is used for the URL segments like `user/:id` would be `params: { id: 5 }`.

**Comment by malinushj** [comment]
@KaniRobinson just beat me to it 😁

**Comment by KaniRobinson** [comment]
if you have url prefixes, such as `/api/v1/users/folders` but also have `api/v1/folder` you can do this on your model
```js
  static methodConf = {
    http: {
      url: '/:prefix/folders'
    },
  }
```
and do the following:
```js
// api/v1/users/folders
Folder.$fetch({
    params: { prefix: 'users' } 
})

// api/v1/folders
Folder.$fetch()
```

If you do not set a prefix, it will remove it from the endpoint ;)

**Comment by KaniRobinson** [comment]
There will be better ways of doing this in the future, just waiting for the all mighty free time haha @malinushj

**Comment by bluetetra** [comment]
Thank you!  That worked for me too.
