### ISSUE TITLE
$delete call the action but does not remove from the store 

### ISSUE THREAD

**Issue by guillaumebriday** [vuex-orm/plugin-axios#63]
Hey!

Since the version `0.32.2` of @vuex-orm/core, the $delete method has some bugs.

I tried to downgrade to `0.32.1` and everything work fine.

The api call is done but the entry is not removed from the store.

There is [lot of changes](https://github.com/vuex-orm/vuex-orm/compare/v0.32.1...v0.32.2) between these two versions and I don't know if it broke something.

Thank you in advance

**Comment by khalidchawtany** [comment]
Delete action uses which currently does not work in vuex-orm :(
```
                model.delete({
                    where: {
                        id: pramas.params.id || data.ids,
                    }
                });
```

**Comment by guillaumebriday** [comment]
You mean that I need to call both `$delete` and `delete` methods as workaround ?

**Comment by khalidchawtany** [comment]
Yup

**Comment by guillaumebriday** [comment]
Ok! do you think it could be fix in this project?

**Comment by khalidchawtany** [comment]
We can change https://github.com/vuex-orm/plugin-axios/blob/456fa5afee0e991fdb48d480caf03ad756a2d516/src/actions/Delete.js#L50-L54
to 
```
static onSuccess(model, params, data) {
    return model.delete(params.params.id || data.id)
  }
```

**Comment by guillaumebriday** [comment]
I opened a PR @khalidchawtany

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
