### ISSUE TITLE
methodConf.http.params ignored

### ISSUE THREAD

**Issue by innovate-invent** [vuex-orm/plugin-axios#68]
There is a bug in version 0.19 of axios that does not merge the params config.
https://github.com/axios/axios/issues/2190

It is recommended to downgrade to 0.18.1 until the issue is resolved.

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

And now this should work fine since Vuex ORM Axios is passing whole config directly down to the Axios instance.
