### ISSUE TITLE
Get parameter array with key value

### ISSUE THREAD

**Issue by guillaumebriday** [vuex-orm/plugin-axios#69]
Hey!

I got the same problem explained in this issue https://github.com/axios/axios/issues/1093.

I'm not sure that is possible to do this in this plugin. As far as I unsterstand, this method is responsible to handle the query params https://github.com/vuex-orm/plugin-axios/blob/70cc314bef15cae65bad9b973f5a255c93b11415/src/actions/Action.js#L61 and does not allow to deal with array as params right ?

```js
const filter = {
  start_at: new Date().toISOString()
}

TimeEntry.$fetch({
  query: {
    filter: filter
  }
})

// At this moment the endpoint should be : /filter[start_at]=2019-10-05T22:00:00.000Z
```

If you confirm my point, I will try to open a PR to allow that behaviour.

Thank you

**Comment by guillaumebriday** [comment]
Maybe with something like that:

```js
endpoint = Object.entries(config.query).map(([k, v]) => {
  if (typeof v === 'object') {
    // do recursive stuff with object
  } else {
    return `${encodeURIComponent(k)}=${encodeURIComponent(filter[k])}`
  }
}).join('&')
```

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

I'll be closing this issue since the library is quite different now. Please feel free to open another issue if there's anything!
