### ISSUE TITLE
override axios instance doesn't work

### ISSUE THREAD

**Issue by mean-cj** [vuex-orm/plugin-axios#71]
Hello 

i cannot override axios instance 
i found bug , the promise not return with ajax original response.

```
  export default ({ $axios }) => {
    VuexORM.use(VuexORMAxios, {
      database,
      http: {
        axios: $axios 
      }
    })
  })
```

```
      TEST.$create({
        data: {     }
      })
        .then((response) => {
          console.log(response)
        })
        .catch((error) => {
          console.log(error)
        })
```

Thank you

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

Now you can pass your own axios instance directly!
