### ISSUE TITLE
Support various API Response Structures by allowing a callback to format Data

### ISSUE THREAD

**Issue by olivergiess** [vuex-orm/plugin-axios#77]
Currently the plugin only supports a rigid API structure which does not include some of the popular standards like JSON:API given the example below for relationships.

Following JSON:API standard relationships will not be populated into models due to the response structure of the standard (see below). 

```
{
    data: {
        id: 1,
        username: "test",
        relationships: {
            posts: {
                data: [{
                    id: 1,
                    title: "Title",
                    body: "Body",
                    user_id: 1,
                }]
            }
        }
    }
}
```

With the current implementation the response from the API is expected to be built for Vuex-ORM `insertOrUpdate()` expects an object of the following structure.

```
{
    data: {
        id: 1,
        username: "test",
        posts: [{
                id: 1,
                title: "Title",
                body: "Body",
                user_id: 1,
            }]
        }
    }
}
```

I there for suggest that we change:

```
  private getDataFromResponse (response: AxiosResponse, config: Config): any {
    if (!config.dataKey) {
      return response.data
    }

    return response.data[config.dataKey]
  }
```

To be:

```
  private getDataFromResponse(response: AxiosResponse, config: Config): any {
    if (!config.dataTransformer) {
      return response.data
    }

    return config.dataTransformer(response);
  }
```

This will allow the package to support any number of API response formats, by allowing the user to intercept and transform the response into a suitable format for Vue-ORM.

**Comment by guillaumebriday** [comment]
Hey!

Just to be sure, before 1.7 we could do something like that:
```js
import JsonApiResponseConverter from 'json-api-response-converter'

VuexORM.use(VuexORMAxios, {
  database,
  http: {
    onResponse (response) {
      return new JsonApiResponseConverter(response.data).formattedResponse
    }
  }
}
```

I built json-api-response-converter to convert Json:API formatted responses to be handle by Vuex-orm axios.

How should I do now ? I see nothing close to this option except this issue. Do you need that we open a PR ?

Thank you in advance 🙏

**Comment by guillaumebriday** [comment]
I opened a PR, your feedbacks are welcome @olivergiess @kiaking 👍

**Comment by guillaumebriday** [comment]
With the PR, we should be able to do something like that:

```js
import JsonApiResponseConverter from 'json-api-response-converter'

User.api().get('/api/users', {
  dataTransformer: (response) => {
    if (response.data === null) {
      return
    }
    // Do wathever we want with the whole response

    return new JsonApiResponseConverter(response.data).formattedResponse
  }
})
```

I hope you will take a look a this repo: [json-api-response-converter](https://github.com/guillaumebriday/json-api-response-converter), it is designed for Vuex-orm 👍

**Comment by kiaking** [comment]
@guillaumebriday Thank you so much! I've made some comment on the PR.

I didn't know about this package! It's awesome 👍 👍 👍

**Comment by olivergiess** [comment]
@guillaumebriday 

Thanks guilla beat me to it!

Nice package I think I'll use it.

**Comment by guillaumebriday** [comment]
Thank you guys! 😊

**Comment by kiaking** [comment]
This is now possible with Vuex ORM Axios 0.8.0! 🎉 Thanks to @guillaumebriday for the wonderful PR!
https://github.com/vuex-orm/plugin-axios/releases/tag/v0.8.0
