### ISSUE TITLE
Documentation: Note on Delete Method

### ISSUE THREAD

**Issue by crazymind** [vuex-orm/plugin-axios#79]
Perhaps I will  be the only one who ran into it, but I think it would make the documentation clearer if the ID would not be 1. I thought `delete: 1` would stand for `delete: true` instead of the ID itself.

```
// better
User.api().delete('/api/users/99', {
  delete: 99
})

// or
const id = 1
User.api().delete(`/api/users/${id}`, {
  delete: id
})
```

**Comment by kiaking** [comment]
Ah, interesting! Yeah, I think it would make sense to use some random number on that argument. Thanks for the feedback!

**Comment by kiaking** [comment]
I've updated the value to `42`! 👍
