### ISSUE TITLE
error ajax response is empty // TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mean-cj** [vuex-orm/plugin-axios#82]
Hello

found error if ajax response is empty or null or cannot connect to api server
"TypeError: Cannot convert undefined or null to object"

```
    return this.model.insertOrUpdate({
      **data: this.getDataFromResponse(response, config) || []**
    })
```

Fixed
```
  private async persistResponseData(
    response: AxiosResponse,
    config: Config
  ): Promise<Collections | null> {
    if (!config.save) {
      return null
    }

    if (config.delete !== undefined) {
      await this.model.delete(config.delete as any)

      return null
    }

    return this.model.insertOrUpdate({
      data: this.getDataFromResponse(response, config) || []
    })
  }
```

**Comment by kiaking** [comment]
Ah interesting. Not sure how to deal with this problem correctly. For network connection error, it should be handled as an error by axios. As part of Vuex ORM, it's not OK to pass null or undefined, but also `number`, `string`, or `boolean` too. The data has to be either Object or and Array.

Maybe we should warn user or even throw error in case of data being other than Object or Array?

**Comment by phaust** [comment]
I have similar problem when using `api().delete()`. When triggering the call, I get console error: `TypeError: can't convert null to object`.

I currently use this workaround: `api().delete('some/url', { delete: null })` which doesn't throw an error.

**Comment by mean-cj** [comment]
Is it possible to check first before call insertOrUpdate

```
  const response = this.getDataFromResponse(response, config)
  if( ! response ) return Promise.reject(new Error('response is null'))
  return this.model.insertOrUpdate({
      data: response
    })

```

**Comment by kiaking** [comment]
Yeah, that could be a solution. Let's add a feature to warn the user when the response body is not valid data.

**Comment by kiaking** [comment]
Added the warning log in Vuex ORM Axios 0.9.1! 🎉 
https://github.com/vuex-orm/plugin-axios/releases/tag/v0.9.1
