### ISSUE TITLE
Nuxt hot reload error The axios instance is not registered.

### ISSUE THREAD

**Issue by mean-cj** [vuex-orm/plugin-axios#83]
Hello

i follow installation method from
https://vuex-orm.github.io/plugin-axios/guide/setup.html#nuxt-js-integration

after save file on ./models folder
nuxt hot reload show error message on console

vuex-orm-axios.esm.js?e72b:97 

Uncaught (in promise) Error: [Vuex ORM Axios] The axios instance is not registered. Please register the axios instance to the model.

    at Request.get [as axios] (vuex-orm-axios.esm.js?e72b:97)
    at Request.eval (vuex-orm-axios.esm.js?e72b:182)
    at step (vuex-orm-axios.esm.js?e72b:58)
    at Object.eval [as next] (vuex-orm-axios.esm.js?e72b:39)
    at eval (vuex-orm-axios.esm.js?e72b:32)
    at new Promise (<anonymous>)
    at __awaiter (vuex-orm-axios.esm.js?e72b:28)
    at Request.request (vuex-orm-axios.esm.js?e72b:176)
    at Request.get (vuex-orm-axios.esm.js?e72b:139)
    at Request.fetch (Zone.js?76c1:35)

Thank you .

**Comment by mean-cj** [comment]
that fixed

// plugins\vuex-orm-axios.js
```
import Vue from 'vue'
import Vuex from 'vuex'
import VuexORM, { Model } from '@vuex-orm/core'
import VuexORMAxios from '@vuex-orm/plugin-axios'
import VuexORMDatabase from '@/models/index.js'

Vue.use(Vuex)
VuexORM.use(VuexORMAxios)

export default ({ $axios }) => {
  Model.setAxios($axios)

  return new Vuex.Store({
    plugins: [VuexORM.install(VuexORMDatabase)]
  })
}
```

// models\index.js
```
import VuexORM, { Model } from '@vuex-orm/core'

const database = new VuexORM.Database()

const fileModels = require.context('.', true, /\.js$/)

fileModels.keys().forEach((fileName) => {
  if (fileName === './index.js') return

  const classOnModel = fileModels(fileName)

  for (const className in classOnModel) {
    if (classOnModel[className].prototype instanceof Model) {
      const vuexModule = classOnModel[`${classOnModel[className].name}Vuex`]
      if (vuexModule !== undefined) {
        database.register(classOnModel[className], vuexModule)
      } else {
        database.register(classOnModel[className])
      }
    }
  }
})
export default database
```

// nuxt.config.js
{
  plugins: [
    '@plugins/vuex-orm-axios',
  ],
  modules: [
    '@nuxtjs/axios'
  ],
}

**Comment by kiaking** [comment]
Hah, never experienced this issue. Is it possible that you have another plugin that tries to use Axios feature with Vuex ORM...?

**Comment by mean-cj** [comment]
Hello 
I have axios plugin for handle ajax response.
I think it should be problem.
Thank you

**Comment by steven0811** [comment]
Even this issue was closed, but not solved, every time I save the `/modes/Post.ts` file, console will log this error when Hot reload finish.

I'm using Nuxt.js + Typescript + This plugin.

![Screen Shot 2020-02-27 at 4 17 45 PM](https://user-images.githubusercontent.com/4948562/75425126-0baea380-597d-11ea-8742-a98a675a19bc.png)

**Comment by kiaking** [comment]
Hmmm... Yeah, I think we need a better way to support Nuxt... Need to think deep on this.

**Comment by larryh** [comment]
Happened to me, too, in a newly-created Nuxt project with the players in this scenario, i.e. all versions should be latest-and-greatest.

When I first fire up the app in Dev Mode and try to do a "get" on a button-click I get this error and no request goes through. After I refresh the page it works fine.

Good luck with the deep thinking... and thank you!

**Comment by mean-cj** [comment]
**My current method on Nuxt**

**store/index.js**
```
import Vuex from 'vuex'
import VuexORM, { Model } from '@vuex-orm/core'
import VuexORMAxios from '@vuex-orm/plugin-axios'

VuexORM.use(VuexORMAxios)

const database = new VuexORM.Database()
const requireComponent = require.context(
  '@/models', // The relative path of the components folder
  true, // Scan includes subfolders
  /\.(js)$/ // The regular expression used to match base component filenames
)
requireComponent.keys().forEach(fileName => {
  const model = requireComponent(fileName)

  if (model.default && model.default.prototype instanceof Model) {
    if (model.VuexModule) {
      database.register(model.default, model.VuexModule)
    } else {
      database.register(model.default)
    }
  }
})

export const plugins = [VuexORM.install(database)]
```

**plugins/vuex-orm-axios.js**
```
import { Model } from '@vuex-orm/core'
export default ({ $axios }) => {
  Model.setAxios($axios)
}
```

**Comment by afuno** [comment]
@kiaking I have this problem when I edit the code of a model that communicates with axios via the Vuex ORM.

```ts
// store/index.ts

import VuexORM from '@vuex-orm/core'
import VuexORMAxios from '@vuex-orm/plugin-axios'

import database from '@/database'

// eslint-disable-next-line import/no-named-as-default-member
VuexORM.use(VuexORMAxios)

export const plugins = [
  // eslint-disable-next-line import/no-named-as-default-member
  VuexORM.install(database)
]

export const strict = true
```

```ts
// database/index.ts

import { Database } from '@vuex-orm/core'
import User from '@/models/user'

const database = new Database()

database.register(User)

export default database
```

```ts
// models/user.ts

import { Model } from '@vuex-orm/core'

export default class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      $id: this.string(null),
      fullName: this.string(null)
    }
  }

  static getAll () {
    return this.api().getAll({ persistBy: 'create' })
  }

  static apiConfig = {
    actions: {
      getAll: {
        method: 'get',
        url: '/users/all'
      }
    }
  }
}
```

The problem comes from having this code:

```ts
static apiConfig = {
  actions: {
    getAll: {
      method: 'get',
      url: '/users/all'
    }
  }
}
```

Scenario:

1. I load the page, everything is fine;
2. I add the comment `// test` anywhere in the model code;
3. I save the file in the editor;
4. Nuxt rebuilds the code automatically and I see an error: `[Vuex ORM Axios] The axios instance is not registered. Please register the axios instance to the model.`

How to fix it?
