### ISSUE TITLE
request to add a method('get/post/patch/put/delete') to api

### ISSUE THREAD

**Issue by vesper8** [vuex-orm/plugin-axios#88]
currently the built-in methods are .get() .post() .patch() .put() .delete(), but I often find myself in functions that can handle multiple different methods, with regular axios rather than do `axios.post()` or `axios.patch()` I prefer to use 

```
      axios({
        method: this.mode === 'add' ? 'post' : 'patch',
        url: `${this.api[this.mode]}`,
        data: this.form,
      })
```

This way I don't have to write two almost identical functions or do an ugly if/else

Would it be possible to add this to this plugin? so that I could do something like

```
User.api().method(this.mode === 'add' ? 'post' : 'patch').url(`${this.api[this.mode]}`).data(this.form)
```

Or it could also be like

```
User.api({
        method: this.mode === 'add' ? 'post' : 'patch',
        url: `${this.api[this.mode]}`,
        data: this.form,
      })
```

Something like this would be nice and more flexible.. hope you consider it. Thanks!

**Comment by kiaking** [comment]
@vesper8 YES! The method you want is `request`.

```js
User.api().request({
  method: this.mode === 'add' ? 'post' : 'patch',
  url: `${this.api[this.mode]}`,
  data: this.form,
})
```

The `request` method is equivalent to `axios()` 👍

**Comment by MeldunKitty** [comment]
Hello! Can you add data argument for api().delete(url, config)? For example api().delete(url, **data,** config)
I have scripts for mass deleting records, when I need DELETE header to send record identifiers and it seems to me that it is not very convenient to use a configurable query for such cases.
Ty!

**Comment by cuebit** [comment]
@MeldunKitty – all request methods mimic the same pattern as axios' request method aliases. I can only sense a level of confusion with end-users if this were to change. Sorry if this is an undesirable side-effect for you.

**Comment by kiaking** [comment]
@MeldunKitty Yea, as @cuebit mentioned, I think API should be exact same as axios methods. Also, I don't think `DELETE` http method accept body either.

Closing this issue since I think the original question was answered.
