### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by mario-minati** [vuex-orm/plugin-axios#9]
We try to handle errors using the onError function which we set during creation of plugin (with config).
The error method is processed nicely (we just added a "console.log" command).

But nevertheless the Devtools console show an unhandled error:
![image](https://user-images.githubusercontent.com/1096532/48677413-0d33ce00-eb75-11e8-8ca8-001fd314eb2d.png)

What can be done to catch the promise nicely?

Best greets,
Mario Minati

**Comment by vesper8** [comment]
You can catch errors and handle success like you normally would this way:

```
        Post.$create({
          data,
        })
          .then((response) => {
            console.log('success', response);
          })
          .catch((response) => {
            console.log('error', response.message, response.errors);
            this.errors = response.errors;
          });
```

**Comment by kiaking** [comment]
The brand new Axios plugin is here! It's very different from what it was, so please check out [the docs](https://vuex-orm.github.io/plugin-axios/)!

For this issue, yes you can catch error directly from axios instance.
