### ISSUE TITLE
Can i override default actions as get post put, delete?

### ISSUE THREAD

**Issue by AlekseyPn** [vuex-orm/plugin-axios#91]
For example i need to override get,post,put,delete, because i use 0.5.1v and i need to migrate from this version to new version easy.

And can i call after override Use.api().get(config) or User.api().post(data, config), without pass url?

**Comment by kiaking** [comment]
@AlekseyPn Hi! Sorry for my late reply. You could define those methods at your base model and let other models extend it!

**Comment by AlekseyPn** [comment]
I tried override methods and all works perfectly, thanks for answer
